### ISSUE TITLE
Pinned comment prevents display of all comments

### ISSUE THREAD

**Issue by rmarquis** [mortbauer/aur-comment-fetcher#7]
Since the AUR 4.2.0 release, users can "pin" a single comment on top in the comments list. Although aur-comment-fetcher succeed in displaying this pinned comment, others comment can't be displayed anymore. Using the `-n` flag has no effect.

On a side note, it would also be useful if the pinned comment could be highlighted in some way.

**Comment by silentboatman** [comment]
I fixed this bug and I'll make a PR later today/tonight.

I agree with @rmarquis, it should be highlighted in some way. Or else it would just be confusing with comments showing up multiple times and in the wrong order.. Any suggestions on how to highlight them? Bold, another color, ..? Right now I just print out "Pinned comment" on the same line as the comments "header".

**Comment by rmarquis** [comment]
Great! I'd use another color together with a "Pinned comment" in the header, but feel free to chose a combination that pleases you!

**Comment by mortbauer** [comment]
Works with #8 , therefore closing, thank you both!
